[package]
name = "dependency-graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
dot = "0.1.4"
serde = "1.0.181"
toml = "0.7.6"
